### ISSUE TITLE
opencv/cv.h: No such file or directory

### ISSUE THREAD

**Issue by wangqingjia1999** [2mulin/MyWebServer#1]
## 问题描述
```
[build] /home/bitate/MyWebServer/include/requestData.h:23:10: fatal error: opencv/cv.h: No such file or directory
[build]    23 | #include <opencv/cv.h>
[build]         |          ^~~~~~~~~~~~~
```

## 解决方法
Ubuntu 安装 opencv 库：
```
sudo apt update
sudo apt install python3-opencv
```
参考这个：https://linuxize.com/post/how-to-install-opencv-on-ubuntu-18-04/

## 建议
1. 在 README.md 中加入说明：需要 python 的 opencv 库的支持；
2. 这个库体积比较大，可以考虑自己造轮子实现自己所需的功能。

**Comment by RedDragon-ling** [comment]
还没写完呢........肯定一堆错。
等我搞明白了，会在README.md写清楚的。

我安装是这两个，头文件就有了，但是还没调试过。
``` bash
yum install opencv
yum install opencv-devel
```

**Comment by RedDragon-ling** [comment]
ttt

**Comment by RedDragon-ling** [comment]
> 还没写完呢........肯定一堆错。
> 等我搞明白了，会在README.md写清楚的。
> 
> 我安装是这两个，头文件就有了，但是还没调试过。
> 
> ```shell
> yum install opencv
> yum install opencv-devel
> ```

**Comment by Bitate** [comment]
抱歉，忘了说明我的操作系统是Ubuntu的，`sudo apt install` 是Ubuntu安装依赖的命令。

我也在写 HTTP 服务器，咱们可以考虑合作合作😀

**Comment by RedDragon-ling** [comment]
我比较菜，也是在自己看书学，可能是你带我做😂😂，不是合作

**Comment by Bitate** [comment]
请问，目前在着手做哪方面呢？

**Comment by RedDragon-ling** [comment]
不太懂你什么意思，我是想做C++服务器的，或者C++相关的，因为我对C++比较感兴趣，也是学的最久的一门语言了

**Comment by Bitate** [comment]
😀就是服务器的哪一部分？HTTP请求和响应处理？URI处理？日记系统？还是其他的

**Comment by RedDragon-ling** [comment]
要分这么详细的吗？我现在这个项目在做线程池那一部分了，我以前做的请求和响应都比较简单，就get、post，404 not Found，200 OK就完事了，你不会是要实现所有http方法吧？日志系统以前看过一个视频，有个人写了log4j，不过我后面没太看懂

**Comment by Bitate** [comment]
https://github.com/yhirose/cpp-httplib
这个开源项目里面一些实现可以参考。

**Comment by Bitate** [comment]
HTTP状态码的处理是一个棘手并且特别关键的部分，这部分我建议多花点时间。

**Comment by Bitate** [comment]
我对状态码的处理是一知半解的状态。

**Comment by RedDragon-ling** [comment]
涨知识了，这个6000多行的代码，我得看多久😂

**Comment by Bitate** [comment]
挑其中能用上的函数看，比如看他线程池怎么实现的

**Comment by RedDragon-ling** [comment]
嗯嗯，我是得好好看看
